name: Main

on:
  push:
    branches:
      - main

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirement.txt
    - name: Run Python scripts
      run: |
        python medician_copy.py 
        python hospital_info_copy.py
